apiVersion: v1
kind: Pod
metadata:
  name: webshell
spec:
  containers:
  - name: webshell
    image: bwsw/webshell
    ports:
    - containerPort: 80
      hostPort: 8018
      protocol: TCP
    securityContext:
      privileged: true
      allowPrivilegeEscalation: true
      seccompProfile:
        type: Unconfined
    env:
    - name: ALLOWED_NETWORKS
      value: "0.0.0.0/0"
  restartPolicy: Always
